#!/usr/bin/env python3
import sys

def is_valid_term(term):
    term = term.strip()
    print(f"Validating term: {term}")
    if "*" not in term:
        try:
            float(term)
            return True
        except ValueError:
            return False

    if term.count("*") != 1:
        return False

    coef_part, x_part = term.split("*")

    coef_part = coef_part.strip()
    x_part = x_part.strip()

    try:
        float(coef_part)
    except ValueError:
        return False

    if not x_part.startswith("X"):
        return False

    if x_part.count("^") != 1:
        return False

    variable, power = x_part.split("^")

    if variable != "X":
        return False

    try:
        int(power)
    except ValueError:
        return False

    return True

def parse_term(term):
    # print(f"Parsing term: {term}")
    if "*" not in term:
        coef = float(term.replace(" ", ""))
        power = 0
        return power, coef

    coef_part, x_part = term.split("*")
    coef_part = coef_part.strip().replace(" ", "")
    coef = float(coef_part)

    x_part = x_part.strip()
    power = int(x_part.split("^")[1])

    return power, coef


def parse_side(side):
    poly = {}

    side = side.replace("-", "+-")
    terms = side.split("+")

    for term in terms:
        term = term.strip()

        if term == "":
            continue
        if not is_valid_term(term):
            print(f"Syntax error: '{term}'")
            exit(1)
    
        power, coef = parse_term(term)
        poly[power] = poly.get(power, 0) + coef
      

    return poly

def reduce_equation(left_poly, right_poly):

    reduced = {}

    for power in left_poly:
        reduced[power] = left_poly[power]

    for power in right_poly:

        if power in reduced:
            reduced[power] = reduced[power] - right_poly[power]
        else:
            reduced[power] = -right_poly[power]
    # print(f"Reduced polynomial: {reduced}")
    return reduced

def get_degree(poly):
    degree = 0

    for power in poly:
        coef = poly[power]

        if coef != 0 and power > degree:
            degree = power

    return degree

def format_number(number):
    if number == int(number):
        return int(number)
    return f"{number:.6f}".rstrip("0").rstrip(".")

def print_reduced_form(poly):

    mathematical_expression = ""

    for power in sorted(poly.keys()):
        coef = poly[power]

        if coef == 0:
            continue
        elif mathematical_expression == "":
            mathematical_expression += f"{coef} * X^{power}"
        elif coef > 0:
            mathematical_expression += f" + {coef} * X^{power}"
        else:
            mathematical_expression += f" - {abs(coef)} * X^{power}"

    print(f"Reduced form: {mathematical_expression} = 0")



def solve_degree_0(poly):
    c = poly.get(0, 0)

    if c == 0:
        print("Any real number is a solution.")
    else:
        print("No solution.")



def solve_degree_1(poly):
    c = poly.get(0, 0)
    b = poly.get(1, 0)

    solution = -c / b

    print("The solution is:")
    print(solution)


def solve_degree_2(poly):
    a = poly.get(2, 0)
    b = poly.get(1, 0)
    c = poly.get(0, 0)

    discriminant = b**2 - 4*a*c

    print(f"Discriminant: {discriminant}")

    if discriminant > 0:
        root1 = (-b - discriminant**0.5) / (2*a)
        root2 = (-b + discriminant**0.5) / (2*a)
        print("Discriminant is strictly positive, the two solutions are:")
        print(f"{format_number(root1)}")
        print(f"{format_number(root2)}")
    elif discriminant == 0:
        root = -b / (2*a)
        print("Discriminant is zero, the solution is:")
        print(f"{format_number(root)}")
    else:
        print("Discriminant is strictly negative, the two complex solutions are:")
        print(f"{format_number(-b)} / {format_number(2*a)} + {format_number((abs(discriminant)**0.5))}i/{format_number(2*a)}")
        print(f"{format_number(-b)} / {format_number(2*a)} - {format_number((abs(discriminant)**0.5))}i/{format_number(2*a)}")


def main():
    equation = ""
    if len(sys.argv) == 2:
        equation = sys.argv[1]
    else:
        print("Usage: python computor.py \"equation\"")
        return


    if equation.count("=") != 1:
        print("Syntax error: equation must contain exactly one '='")
        return

    left, right = equation.split("=")

    if left.strip() == "" or right.strip() == "":
        print("Syntax error: empty side")
        return

    left_poly = parse_side(left)
    right_poly = parse_side(right)

    reduced = reduce_equation(left_poly, right_poly)
    print_reduced_form(reduced)

    print(f"Polynomial degree: {get_degree(reduced)}")
    
    degree = get_degree(reduced) 
    if degree == 0:
        solve_degree_0(reduced)
    elif degree == 1:
        solve_degree_1(reduced)
    elif degree == 2:
        solve_degree_2(reduced)
    else:
        print("The polynomial degree is strictly greater than 2, I can't solve.")
if __name__ == "__main__":
    main()