#!/usr/bin/env python3
import sys

def is_valid_term(term):
    term = term.strip().replace(" ", "")

    if term == "":
        return False

    if term.count("*") > 1:
        return False

    try:
        parse_term(term)
        return True
    except:
        return False

def parse_term(term):
    term = term.strip().replace(" ", "")

    # Case: simple number => 5 means 5 * X^0
    if "X" not in term:
        coef = float(term)
        power = 0
        return power, coef

    # Case: contains X
    if term.count("X") != 1:
        raise ValueError("Invalid term")

    before_x, after_x = term.split("X")
    

    # Find coefficient
    if before_x == "":
        coef = 1.0
    elif before_x == "+":
        coef = 1.0
    elif before_x == "-":
        coef = -1.0
    else:
        if before_x.endswith("*"):
            before_x = before_x[:-1]
        coef = float(before_x)

    # Find power
    if after_x == "":
        power = 1
    else:
        if not after_x.startswith("^"):
            raise ValueError("Invalid term")

        power_text = after_x[1:]

        if power_text == "":
            raise ValueError("Invalid power")

        power = int(power_text)

        if power < 0:
            raise ValueError("Negative power")

    return power, coef

def parse_side(side):
    poly = {}

    side = side.replace("-", "+-")
    terms = side.split("+")

    for term in terms:
        term = term.strip()

        if term == "":
            continue
        if not is_valid_term(term):
            print(f"Syntax error: '{term}'")
            exit(1)
    
        power, coef = parse_term(term)
        poly[power] = poly.get(power, 0) + coef
      

    return poly

def reduce_equation(left_poly, right_poly):

    reduced = {}

    for power in left_poly:
        reduced[power] = left_poly[power]

    for power in right_poly:

        if power in reduced:
            reduced[power] = reduced[power] - right_poly[power]
        else:
            reduced[power] = -right_poly[power]
    # print(f"Reduced polynomial: {reduced}")
    return reduced

def get_degree(poly):
    degree = 0

    for power in poly:
        coef = poly[power]

        if coef != 0 and power > degree:
            degree = power

    return degree

def format_number(number):
    if number == int(number):
        return int(number)
    return f"{number:.6f}".rstrip("0").rstrip(".")

def print_reduced_form(poly):

    mathematical_expression = ""

    for power in sorted(poly.keys()):
        coef = poly[power]

        if coef == 0:
            continue
        elif mathematical_expression == "":
            mathematical_expression += f"{format_number(coef)} * X^{power}"
        elif coef > 0:
            mathematical_expression += f" + {format_number(coef)} * X^{power}"
        else:
            mathematical_expression += f" - {format_number(abs(coef))} * X^{power}"
    if mathematical_expression == "":
        mathematical_expression = "0 * X^0"
    print(f"Reduced form: {mathematical_expression} = 0")



def solve_degree_0(poly):
    c = poly.get(0, 0)

    if c == 0:
        print("Any real number is a solution.")
    else:
        print("No solution.")



def solve_degree_1(poly):
    c = poly.get(0, 0)
    b = poly.get(1, 0)

    solution = -c / b

    print("The solution is:")
    print(format_number(solution))

def gcd(a, b):
    a = abs(int(a))
    b = abs(int(b))

    smallest = a

    if b < a:
        smallest = b

    greatest_divisor = 1

    i = 1
    while i <= smallest:
        if a % i == 0 and b % i == 0:
            greatest_divisor = i
        i += 1

    return greatest_divisor

def reduce_fraction(numerator, denominator):
    divisor = gcd(numerator, denominator)

    new_numerator = numerator // divisor
    new_denominator = denominator // divisor

    if new_denominator < 0:
        new_numerator = -new_numerator
        new_denominator = -new_denominator

    return new_numerator, new_denominator

def solve_degree_2(poly):
    a = poly.get(2, 0)
    b = poly.get(1, 0)
    c = poly.get(0, 0)

    discriminant = b**2 - 4*a*c

    # print(f"Discriminant: {discriminant}")

    if discriminant > 0:
        root1 = (-b - discriminant**0.5) / (2*a)
        root2 = (-b + discriminant**0.5) / (2*a)
        print("Discriminant is strictly positive, the two solutions are:")
        print(f"{format_number(root1)}")
        print(f"{format_number(root2)}")
    elif discriminant == 0:
        root = -b / (2*a)
        print("Discriminant is zero, the solution is:")
        print(f"{format_number(root)}")
    else:
        print("Discriminant is strictly negative, the two complex solutions are:")
        real_num, real_den = reduce_fraction(int(-b), int(2 * a))
        imag_num, imag_den = reduce_fraction(int(abs(discriminant) ** 0.5), int(2 * a))
        print(f"{real_num}/{real_den} + {imag_num}i/{imag_den}")
        print(f"{real_num}/{real_den} - {imag_num}i/{imag_den}")

def main():
    equation = ""
    if len(sys.argv) == 2:
        equation = sys.argv[1]
    elif len(sys.argv) < 2:
        equation = input("Enter an equation: ")
    elif len(sys.argv) > 2:
        print("Usage: python computor.py \"equation\"")
        return


    if equation.count("=") != 1:
        print("Syntax error: equation must contain exactly one '='")
        return

    left, right = equation.split("=")

    if left.strip() == "" or right.strip() == "":
        print("Syntax error: empty side")
        return

    left_poly = parse_side(left)
    right_poly = parse_side(right)

    reduced = reduce_equation(left_poly, right_poly)
    print_reduced_form(reduced)

    print(f"Polynomial degree: {get_degree(reduced)}")
    
    degree = get_degree(reduced) 
    if degree == 0:
        solve_degree_0(reduced)
    elif degree == 1:
        solve_degree_1(reduced)
    elif degree == 2:
        solve_degree_2(reduced)
    else:
        print("The polynomial degree is strictly greater than 2, I can't solve.")
if __name__ == "__main__":
    main()